### PR TITLE
show-hide river settings in river-mongodb plugin

### PR DESCRIPTION
**Pull request by ewgRa**
This pull request change how MongoDB River Administration looks like. Instead of show all river settings, there is button, and you can hide/show settings for specific river.

### CODE REVIEW

**Comment by benmccann** [comment]
Can you add before & after screenshots to help us review this more easily?

**Comment by ewgRa** [comment]
Done. This PR, because typical usage of this page is to stop/start river, or checking river settings for specific river. Show settings each time for each rivers is not so usable.

**Old**:
old

**New**:
new

**Comment by ewgRa** [comment]
Wait please 10 min. There is also one change that I forget

**Comment by ewgRa** [comment]
Done. There is new screenshot with some notices.

new

**Pull request merged**
